Repository realworld-spring/spring-boot, pull requests merged in 2023-08, with the labels that each got.

#1 [Feature] 엔티티 구현 및 application 설정 파일 작성
  build.gradle
  favicon.png
  src/main/java/real/world/config/JpaConfig.java
  src/main/java/real/world/config/SecurityConfig.java
  src/main/java/real/world/domain/article/entity/Article.java
  src/main/java/real/world/domain/article/entity/Comment.java
  src/main/java/real/world/domain/article/entity/Favorite.java
  src/main/java/real/world/domain/article/entity/Tag.java
  src/main/java/real/world/domain/article/entity/TagArticle.java
  src/main/java/real/world/domain/follow/entity/Follow.java
  src/main/java/real/world/domain/user/entity/User.java
  src/main/resources/application-data-local.yml
  src/main/resources/application-web-local.yml
  src/main/resources/application.yml
Labels: enhancement

#2 [Chore] mariaDB로 연동 변경
  build.gradle
  src/main/resources/application-data-local.yml
Labels: chore

#4 [Test] User 도메인, 회원가입 테스트 작성
  build.gradle
  src/main/java/real/world/domain/user/controller/UserController.java
  src/main/java/real/world/domain/user/dto/response/RegisterResponse.java
  src/main/java/real/world/domain/user/entity/User.java
  src/main/java/real/world/domain/user/service/UserService.java
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
  src/test/java/real/world/domain/user/entity/UserTest.java
  src/test/java/real/world/domain/user/service/UserServiceTest.java
  src/test/java/real/world/e2e/RestAssuredUtils.java
  src/test/java/real/world/e2e/UserE2ETest.java
  src/test/java/real/world/fixture/UserFixtures.java
  src/test/resources/application.yml
Labels: test

#5 [Feautre] 예외처리 추가
  src/main/java/real/world/domain/user/entity/User.java
  src/main/java/real/world/domain/user/service/UserService.java
  src/main/java/real/world/error/ErrorCode.java
  src/main/java/real/world/error/ErrorResponse.java
  src/main/java/real/world/error/GlobalExceptionHandler.java
  src/main/java/real/world/error/exception/BusinessException.java
  src/main/java/real/world/error/exception/EmailInvalidException.java
  src/main/java/real/world/error/exception/UsernameAlreadyExistsException.java
  src/main/java/real/world/error/exception/UsernameInvalidException.java
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
  src/test/java/real/world/domain/user/entity/UserTest.java
  src/test/java/real/world/domain/user/service/UserServiceTest.java
Labels: enhancement
