Repository realworld-spring/spring-boot, pull requests merged in 2023-09, with the labels that each got.

#8 [Feature] Restdocs + Swagger-UI 추가
  build.gradle
  src/main/java/real/world/config/SecurityConfig.java
  src/main/resources/application-web-local.yml
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
Labels: enhancement

#11 [Feature] 인증, 인가 구현
  build.gradle
  src/main/java/real/world/config/SecurityConfig.java
  src/main/java/real/world/domain/user/controller/UserController.java
  src/main/java/real/world/domain/user/dto/request/LoginRequest.java
  src/main/java/real/world/domain/user/dto/response/LoginResponse.java
  src/main/java/real/world/domain/user/entity/User.java
  src/main/java/real/world/domain/user/entity/UserRole.java
  src/main/java/real/world/domain/user/repository/UserRepository.java
  src/main/java/real/world/domain/user/service/UserService.java
  src/main/java/real/world/error/ErrorCode.java
  src/main/java/real/world/error/exception/AuthenticationErrorCodeException.java
  src/main/java/real/world/error/exception/UserIdNotExistException.java
  src/main/java/real/world/security/authentication/CustomAuthenticationProvider.java
  src/main/java/real/world/security/authentication/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/real/world/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/real/world/security/jwt/JwtAuthenticationFilter.java
  src/main/java/real/world/security/jwt/JwtAuthenticationProvider.java
  src/main/java/real/world/security/jwt/JwtAuthenticationToken.java
  src/main/java/real/world/security/service/CustomUserDetails.java
  src/main/java/real/world/security/service/CustomUserDetailsService.java
  src/main/java/real/world/security/service/UserDetailsByEmailService.java
  src/main/java/real/world/security/service/UserDetailsByIdService.java
  src/main/java/real/world/security/support/JwtUtil.java
  src/main/java/real/world/security/support/NorRequestMatcher.java
  src/main/java/real/world/security/support/RootNameObjectMapper.java
  src/main/resources/application-web-local.yml
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
  src/test/resources/application.yml
Labels: enhancement

#12 [Feature] LoginArgumentResolver 구현
  build.gradle
  src/main/java/real/world/config/WebMvcConfig.java
  src/main/java/real/world/domain/auth/annotation/Auth.java
  src/main/java/real/world/domain/auth/annotation/AuthArgumentResolver.java
  src/main/java/real/world/domain/user/controller/UserController.java
  src/main/java/real/world/domain/user/service/UserService.java
  src/main/java/real/world/security/jwt/JwtAuthenticationFilter.java
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
  src/test/java/real/world/fixture/UserFixtures.java
  src/test/java/real/world/support/TestSecurityConfig.java
  src/test/java/real/world/support/WithMockUserId.java
  src/test/java/real/world/support/WithMockUserIdFactory.java
Labels: enhancement, test

#14 [Feature] 아티클 업로드 구현
  .gitignore
  build.gradle
  http/article.http
  http/http-client.env.json
  http/user.http
  src/main/java/real/world/domain/article/controller/ArticleController.java
  src/main/java/real/world/domain/article/dto/request/UploadRequest.java
  src/main/java/real/world/domain/article/dto/response/UploadResponse.java
  src/main/java/real/world/domain/article/entity/Article.java
  src/main/java/real/world/domain/article/entity/Tag.java
  src/main/java/real/world/domain/article/entity/TagArticle.java
  src/main/java/real/world/domain/article/repository/ArticleRepository.java
  src/main/java/real/world/domain/article/repository/TagRepository.java
  src/main/java/real/world/domain/article/service/ArticleService.java
  src/main/java/real/world/domain/article/service/SlugTranslator.java
  src/main/java/real/world/domain/article/service/SlugUUIDTranslator.java
  src/main/java/real/world/domain/user/dto/ProfileDto.java
  src/main/resources/application-web-local.yml
  src/test/java/real/world/domain/article/controller/ArticleControllerTest.java
  src/test/java/real/world/fixture/ArticleFixtures.java
Labels: enhancement

#15 [Feature] User 조회, 수정 API 및 Test작성
  src/main/java/real/world/domain/user/controller/UserController.java
  src/main/java/real/world/domain/user/dto/request/UpdateRequest.java
  src/main/java/real/world/domain/user/dto/response/LoginResponse.java
  src/main/java/real/world/domain/user/dto/response/UserResponse.java
  src/main/java/real/world/domain/user/entity/User.java
  src/main/java/real/world/domain/user/service/UserService.java
  src/main/java/real/world/security/jwt/JwtAuthenticationFilter.java
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
  src/test/java/real/world/domain/user/service/UserServiceTest.java
  src/test/java/real/world/e2e/UserE2ETest.java
  src/test/java/real/world/fixture/UserFixtures.java
Labels: enhancement, refactor, test

#16 [Chore] Swagger 제거, Querydsl 추가, /api 처리
  .idea/httpRequests/http-requests-log.http
  build.gradle
  src/main/java/real/world/config/SecurityConfig.java
  src/main/java/real/world/domain/article/controller/ArticleController.java
  src/main/java/real/world/domain/user/controller/UserController.java
  src/main/resources/application-web-local.yml
  src/test/java/real/world/domain/article/controller/ArticleControllerTest.java
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
  src/test/java/real/world/e2e/UserE2ETest.java
  src/test/java/real/world/support/TestSecurityConfig.java
Labels: chore

#17 [Refactor] 아티클에 CQRS 패턴을 적용하여 ArticleView를 통해 조회하도록 수정
  .idea/httpRequests/http-requests-log.http
  src/main/java/real/world/config/JpaConfig.java
  src/main/java/real/world/domain/article/controller/ArticleController.java
  src/main/java/real/world/domain/article/dto/response/ArticleResponse.java
  src/main/java/real/world/domain/article/entity/Article.java
  src/main/java/real/world/domain/article/entity/Tag.java
  src/main/java/real/world/domain/article/entity/TagArticle.java
  src/main/java/real/world/domain/article/query/ArticleQueryRepository.java
  src/main/java/real/world/domain/article/query/ArticleQueryRepositoryImpl.java
  src/main/java/real/world/domain/article/query/ArticleView.java
  src/main/java/real/world/domain/article/repository/TagRepository.java
  src/main/java/real/world/domain/article/service/ArticleQueryService.java
  src/main/java/real/world/domain/article/service/ArticleService.java
  src/main/java/real/world/error/ErrorCode.java
  src/main/java/real/world/error/exception/ArticleNotFoundException.java
  src/test/java/real/world/domain/article/controller/ArticleControllerTest.java
  src/test/java/real/world/domain/article/query/ArticleQueryRepositoryTest.java
  src/test/java/real/world/domain/article/service/ArticleServiceTest.java
  src/test/java/real/world/e2e/ArticleE2ETest.java
  src/test/java/real/world/e2e/E2ETest.java
  src/test/java/real/world/e2e/RestAssuredUtils.java
  src/test/java/real/world/e2e/UserE2ETest.java
  src/test/java/real/world/e2e/util/DBInitializer.java
  src/test/java/real/world/e2e/util/DatabaseCleaner.java
  src/test/java/real/world/fixture/ArticleFixtures.java
  src/test/java/real/world/fixture/UserFixtures.java
Labels: enhancement, refactor, test

#20 [Refactor] 조회용 모델 ProfileDto를 Profile로 수정
  src/main/java/real/world/domain/article/dto/response/ArticleResponse.java
  src/main/java/real/world/domain/profile/dto/response/ProfileResponse.java
  src/main/java/real/world/domain/profile/query/Profile.java
  src/main/java/real/world/domain/profile/query/ProfileQueryRepository.java
  src/main/java/real/world/domain/profile/query/ProfileQueryRepositoryImpl.java
  src/main/java/real/world/domain/profile/repository/ProfileQueryRepository.java
  src/main/java/real/world/domain/profile/service/ProfileQueryService.java
  src/main/java/real/world/domain/user/dto/ProfileDto.java
  src/test/java/real/world/domain/profile/service/ProfileQueryServiceTest.java
Labels: refactor

#21 [Refactor] JSON 매퍼의 Serialization 옵션 제거
  src/main/java/real/world/domain/article/controller/ArticleController.java
  src/main/java/real/world/domain/article/dto/response/ArticleApiResponse.java
  src/main/java/real/world/domain/article/dto/response/ArticleResponse.java
  src/main/java/real/world/domain/profile/controller/ProfileController.java
  src/main/java/real/world/domain/profile/dto/response/ProfileApiResponse.java
  src/main/java/real/world/domain/profile/dto/response/ProfileResponse.java
  src/main/java/real/world/domain/user/controller/UserController.java
  src/main/java/real/world/domain/user/dto/response/UserApiResponse.java
  src/main/java/real/world/domain/user/dto/response/UserResponse.java
  src/main/resources/application-web-local.yml
  src/test/java/real/world/domain/article/controller/ArticleControllerTest.java
  src/test/java/real/world/domain/profile/controller/ProfileControllerTest.java
  src/test/java/real/world/domain/user/controller/UserControllerTest.java
  src/test/java/real/world/domain/user/service/UserServiceTest.java
  src/test/java/real/world/e2e/ArticleE2ETest.java
  src/test/java/real/world/e2e/UserE2ETest.java
Labels: refactor
